### ISSUE TITLE
Support using the library from node js

### ISSUE THREAD

**Issue by santiagoaguiar** [gre/qajax#12]
The code now references `window` and assumes the `XMLHttpRequest` object is available globally. This means that the library cannot be used easily inside node.js.

I think it would be possible to provide a different entry point for node js, and add a dependency to, for example, [xmlhttprequest](https://www.npmjs.org/package/xmlhttprequest), so that we could use the library inside node also.

Also, to support using browserify to bundle the library, a different entry point should be provided using the [`"browser"`](https://gist.github.com/defunctzombie/4339901) field, which is supported by browserify/webpack, where the `window.XMLHttpRequest` object would be used instead.

How does that sound? Should I create a pull request?

**Comment by gre** [comment]
Fixed in Qajax 1.0.0

---

From Node.js:
```javascript
 require("qajax")("http://google.fr/").then(function(res){ console.log(res.responseText); }).done()
```

```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.fr/">here</A>.
</BODY></HTML>
```
